// web-client/apps/zit-vue/src/views/Main.vue
<template>
    <main>
        <ClientInfo
            invoiceNo="0047"
            invoiceDate="26/07/18"
            name="Thinh Pham"
            address="1600 Amphitheatre Pkwy, Mountain View, CA 94043, United States"
        ></ClientInfo>
            <InvoiceDetails :tasks="tasks"></InvoiceDetails>
            <InvoiceTotal
                advance="$21,000.00"
                discount="$645.00"
                total="$64,276.00"
            ></InvoiceTotal>
                <InvoicePay></InvoicePay>
    </main>
</template>
<script lang="ts">
import Vue from 'vue';
import ClientInfo from '@/components/ClientInfo.vue';
import InvoiceDetails from '@/components/InvoiceDetails.vue';
import InvoiceTotal from '@/components/InvoiceTotal.vue';
import InvoicePay from '@/components/InvoicePay.vue';
import { invoiceService } from '../invoice_service';
import { tasks } from '../tasks';

export default Vue.extend({
  name: 'Main',
  components: {
    ClientInfo,
    InvoiceDetails,
    InvoiceTotal,
    InvoicePay,
  },
  data() {
    return {
      tasks,
    };
  },
  async created() {
    const clientInfo = await invoiceService.getClientInfo(this.$route);
  },
});
</script>

// web-client/apps/zit/src/views/Main.tsx
import * as React from 'react';
import ClientInfo from '../components/ClientInfo';
import InvoiceDetails from '../components/InvoiceDetails';
import InvoiceTotal from '../components/InvoiceTotal';
import InvoicePay from '../components/InvoicePay';
import { bindThis } from '../shared';

const items = [
  {
    title: 'Character illustration',
    description: 'Character Design projects from the latest top online portfolios on Behance.',
    rate: 65,
    hours: 84,
  },
  {
    title: 'Cross Heart Charity Branding',
    description:
      'Attempt to attach higher credibility to a new product by associating it with a well established company name.',
    rate: 89,
    hours: 100,
  },
  {
    title: 'iOS App',
    description:
      'A video game franchise inspired primarily by a sketch of stylized wingless ' +
      '- Including Branding/Graphics/Motion Picture & Videos.',
    rate: 100,
    hours: 500,
  },
];

interface State {
  loading: boolean;
}

export default class Main extends React.Component<{}, State> {
  constructor(props: {}) {
    super(props);
    this.state = { loading: false };
  }
  render() {
    return (
      <main>
        <ClientInfo
          name={'Thinh Pham'}
          invoiceNo={'0047'}
          invoiceDate={'2018/08/07'}
          address={'1600 Amphitheatre Pkwy, Mountain View, CA 94043, United States'}
        />
        <InvoiceDetails items={items} />
        <InvoiceTotal advance={21000.0} discount={8} total={64275.0} />
        <InvoicePay
          onStripeToken={this.onStripeToken}
          submitHandler={this.submitHandler}
          loading={this.state.loading}
        />
      </main>
    );
  }

  @bindThis
  submitHandler() {
    this.setState({ loading: true });
  }

  @bindThis
  onStripeToken() {}
}
