// web-client/apps/zit/src/components/ReadMore.tsx
import * as React from 'react';
import styled from 'styled-components';

interface Props {
  text: string;
  length?: number;
}

interface State {
  expanded: boolean;
}

const StyledReadMore = styled.p`
  span:first-of-type {
    margin-right: 5px;
  }
  .hover-underline-animation {
    cursor: pointer;
    display: inline-block;
    position: relative;
    color: $zehitomo-primary;
  }
  .hover-underline-animation::after {
    content: '';
    position: absolute;
    width: 100%;
    transform: scaleX(0);
    height: 1px;
    bottom: 0;
    left: 0;
    background-color: $zehitomo-primary;
    transform-origin: bottom right;
    transition: transform 0.3s ease-out;
  }
  .hover-underline-animation:hover::after {
    transform: scaleX(1);
    transform-origin: bottom left;
  }
`;

export default class ReadMore extends React.Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = { expanded: false };
  }

  render() {
    const length = this.props.length || 50;
    const { text } = this.props;
    const { expanded } = this.state;
    const textWithLength = text.length > length ? text.substring(0, length) : text;
    return (
      <StyledReadMore>
        <span>{expanded ? text : textWithLength}</span>
        <span
          className="hover-underline-animation"
          onClick={() => this.setState({ expanded: !expanded })}
        >
          {' '}
          {expanded ? 'less' : 'more'}
        </span>
      </StyledReadMore>
    );
  }
}

// web-client/apps/zit-vue/src/components/ReadMore.vue
<template>
  <p>
    <span>{{textWithLength}}</span>
    <span
      class="hover-underline-animation"
      @click="expanded = !expanded"
    > {{ expanded ? 'less': 'more'}}</span>
  </p>
</template>

<script src="./ReadMore.ts" lang="ts">
</script>

<style lang="scss" scoped>
p {
  span:first-of-type {
    margin-right: 5px;
  }
}
.hover-underline-animation {
  cursor: pointer;
  display: inline-block;
  position: relative;
  color: $zehitomo-primary;
}
.hover-underline-animation::after {
  content: '';
  position: absolute;
  width: 100%;
  transform: scaleX(0);
  height: 1px;
  bottom: 0;
  left: 0;
  background-color: $zehitomo-primary;
  transform-origin: bottom right;
  transition: transform 0.3s ease-out;
}
.hover-underline-animation:hover::after {
  transform: scaleX(1);
  transform-origin: bottom left;
}
</style>
