// web-client/apps/zit-vue/src/components/BouncingLoader.vue
<template>
    <div class="bouncing-loader">
        <div></div>
        <div></div>
        <div></div>
    </div>
</template>
<script lang="ts">
import Vue from 'vue';
export default Vue.extend({
  name: 'BouncingLoader',
});
</script>

<style lang="scss" scoped>
@keyframes bouncing-loader {
  from {
    opacity: 1;
    transform: translateY(0);
  }
  to {
    opacity: 0.1;
    transform: translateY(-1rem);
  }
}
.bouncing-loader {
  display: flex;
  justify-content: center;
  height: 100%;
}
.bouncing-loader > div {
  width: 1rem;
  height: 1rem;
  margin: 2rem 0.2rem;
  background: #8385aa;
  border-radius: 50%;
  animation: bouncing-loader 0.6s infinite alternate;
}
.bouncing-loader > div:nth-child(2) {
  animation-delay: 0.2s;
}
.bouncing-loader > div:nth-child(3) {
  animation-delay: 0.4s;
}
</style>

// web-client/apps/zit/src/components/BouncingLoader.tsx
import * as React from 'react';
import styled, { keyframes, theme } from '@zit-react/shared';

const bouncingLoader = keyframes`
  from {
    opacity: 1;
    transform: translateY(-0.5rem);
  }

  to {
    opacity: 0.2;
    transform: translateY(0.5rem);
  }
`;

const StyledBouncingLoader = styled.div`
  display: flex;
  justify-content: center;
  height: 100%;
  > div {
    width: 1rem;
    height: 1rem;
    margin: 2rem 0.2rem;
    background: ${theme.accentColor};
    border-radius: 50%;
    animation: ${bouncingLoader} 0.6s infinite alternate;
  }
  > div:nth-child(2) {
    animation-delay: 0.2s;
  }
  > div:nth-child(3) {
    animation-delay: 0.4s;
  }
`;

const BouncingLoader = () => {
  return (
    <StyledBouncingLoader>
      <div />
      <div />
      <div />
    </StyledBouncingLoader>
  );
};

export default BouncingLoader;
